[package]
name = "rustyrays"
version = "0.1.0"
authors = ["Kristian Theilgaard <kth@flowtale.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
